export const LANG_KEYS = {
  ASSEMBLY: 'ASSEMBLY',
  BASH: 'BASH',
  BASIC: 'BASIC',
  C_CLANG_18: 'C_CLANG_18',
  C_CLANG_19: 'C_CLANG_19',
  C_CLANG_7: 'C_CLANG_7',
  CPP_CLANG_7: 'CPP_CLANG_7',
  C_GCC_14: 'C_GCC_14',
  CPP_GCC_14: 'CPP_GCC_14',
  C_GCC_7: 'C_GCC_7',
  CPP_GCC_7: 'CPP_GCC_7',
  C_GCC_8: 'C_GCC_8',
  CPP_GCC_8: 'CPP_GCC_8',
  C_GCC_9: 'C_GCC_9',
  CPP_GCC_9: 'CPP_GCC_9',
  CLOJURE: 'CLOJURE',
  CSHARP_MONO: 'CSHARP_MONO',
  COBOL: 'COBOL',
  COMMON_LISP: 'COMMON_LISP',
  DART: 'DART',
  D_DMD: 'D_DMD',
  ELIXIR: 'ELIXIR',
  ERLANG: 'ERLANG',
  EXECUTABLE: 'EXECUTABLE',
  FSHARP: 'FSHARP',
  FORTRAN: 'FORTRAN',
  GO_1_13: 'GO_1_13',
  GO_1_18: 'GO_1_18',
  GO_1_22: 'GO_1_22',
  GO_1_23: 'GO_1_23',
  GROOVY: 'GROOVY',
  HASKELL: 'HASKELL',
  JAVAFX: 'JAVAFX',
  JAVA_JDK_17: 'JAVA_JDK_17',
  JAVA_OPENJDK_13: 'JAVA_OPENJDK_13',
  JAVASCRIPT_NODE_12: 'JAVASCRIPT_NODE_12',
  JAVASCRIPT_NODE_18: 'JAVASCRIPT_NODE_18',
  JAVASCRIPT_NODE_20: 'JAVASCRIPT_NODE_20',
  JAVASCRIPT_NODE_22: 'JAVASCRIPT_NODE_22',
  KOTLIN_1_3: 'KOTLIN_1_3',
  KOTLIN_2_1: 'KOTLIN_2_1',
  LUA: 'LUA',
  MULTI_FILE_PROGRAM: 'MULTI_FILE_PROGRAM',
  OBJECTIVE_C: 'OBJECTIVE_C',
  OCAML: 'OCAML',
  OCTAVE: 'OCTAVE',
  PASCAL: 'PASCAL',
  PERL: 'PERL',
  PHP_7: 'PHP_7',
  PHP_8: 'PHP_8',
  PLAIN_TEXT: 'PLAIN_TEXT',
  PROLOG: 'PROLOG',
  PYTHON_2: 'PYTHON_2',
  PYTHON_3_11: 'PYTHON_3_11',
  PYTHON_3_12: 'PYTHON_3_12',
  PYTHON_3_13: 'PYTHON_3_13',
  PYTHON_3_8: 'PYTHON_3_8',
  R_4: 'R_4',
  R_4_4: 'R_4_4',
  RUBY: 'RUBY',
  RUST_1_40: 'RUST_1_40',
  RUST_1_85: 'RUST_1_85',
  SCALA: 'SCALA',
  SQL: 'SQL',
  SWIFT: 'SWIFT',
  TYPESCRIPT_3: 'TYPESCRIPT_3',
  TYPESCRIPT_5: 'TYPESCRIPT_5',
  TYPESCRIPT_5_6: 'TYPESCRIPT_5_6',
  VISUAL_BASIC_NET: 'VISUAL_BASIC_NET',
};

export const LANGUAGES_MAP: Record<string, { name: string; id: number }> = {
  [LANG_KEYS.ASSEMBLY]: { name: 'Assembly (NASM 2.14.02)', id: 45 },
  [LANG_KEYS.BASH]: { name: 'Bash (5.0.0)', id: 46 },
  [LANG_KEYS.BASIC]: { name: 'Basic (FBC 1.07.1)', id: 47 },
  [LANG_KEYS.C_CLANG_18]: { name: 'C (Clang 18.1.8)', id: 104 },
  [LANG_KEYS.C_CLANG_19]: { name: 'C (Clang 19.1.7)', id: 110 },
  [LANG_KEYS.C_CLANG_7]: { name: 'C (Clang 7.0.1)', id: 75 },
  [LANG_KEYS.CPP_CLANG_7]: { name: 'C++ (Clang 7.0.1)', id: 76 },
  [LANG_KEYS.C_GCC_14]: { name: 'C (GCC 14.1.0)', id: 103 },
  [LANG_KEYS.CPP_GCC_14]: { name: 'C++ (GCC 14.1.0)', id: 105 },
  [LANG_KEYS.C_GCC_7]: { name: 'C (GCC 7.4.0)', id: 48 },
  [LANG_KEYS.CPP_GCC_7]: { name: 'C++ (GCC 7.4.0)', id: 52 },
  [LANG_KEYS.C_GCC_8]: { name: 'C (GCC 8.3.0)', id: 49 },
  [LANG_KEYS.CPP_GCC_8]: { name: 'C++ (GCC 8.3.0)', id: 53 },
  [LANG_KEYS.C_GCC_9]: { name: 'C (GCC 9.2.0)', id: 50 },
  [LANG_KEYS.CPP_GCC_9]: { name: 'C++ (GCC 9.2.0)', id: 54 },
  [LANG_KEYS.CLOJURE]: { name: 'Clojure (1.10.1)', id: 86 },
  [LANG_KEYS.CSHARP_MONO]: { name: 'C# (Mono 6.6.0.161)', id: 51 },
  [LANG_KEYS.COBOL]: { name: 'COBOL (GnuCOBOL 2.2)', id: 77 },
  [LANG_KEYS.COMMON_LISP]: { name: 'Common Lisp (SBCL 2.0.0)', id: 55 },
  [LANG_KEYS.DART]: { name: 'Dart (2.19.2)', id: 90 },
  [LANG_KEYS.D_DMD]: { name: 'D (DMD 2.089.1)', id: 56 },
  [LANG_KEYS.ELIXIR]: { name: 'Elixir (1.9.4)', id: 57 },
  [LANG_KEYS.ERLANG]: { name: 'Erlang (OTP 22.2)', id: 58 },
  [LANG_KEYS.EXECUTABLE]: { name: 'Executable', id: 44 },
  [LANG_KEYS.FSHARP]: { name: 'F# (.NET Core SDK 3.1.202)', id: 87 },
  [LANG_KEYS.FORTRAN]: { name: 'Fortran (GFortran 9.2.0)', id: 59 },
  [LANG_KEYS.GO_1_13]: { name: 'Go (1.13.5)', id: 60 },
  [LANG_KEYS.GO_1_18]: { name: 'Go (1.18.5)', id: 95 },
  [LANG_KEYS.GO_1_22]: { name: 'Go (1.22.0)', id: 106 },
  [LANG_KEYS.GO_1_23]: { name: 'Go (1.23.5)', id: 107 },
  [LANG_KEYS.GROOVY]: { name: 'Groovy (3.0.3)', id: 88 },
  [LANG_KEYS.HASKELL]: { name: 'Haskell (GHC 8.8.1)', id: 61 },
  [LANG_KEYS.JAVAFX]: { name: 'JavaFX (JDK 17.0.6, OpenJFX 22.0.2)', id: 96 },
  [LANG_KEYS.JAVA_JDK_17]: { name: 'Java (JDK 17.0.6)', id: 91 },
  [LANG_KEYS.JAVA_OPENJDK_13]: { name: 'Java (OpenJDK 13.0.1)', id: 62 },
  [LANG_KEYS.JAVASCRIPT_NODE_12]: { name: 'JavaScript (Node.js 12.14.0)', id: 63 },
  [LANG_KEYS.JAVASCRIPT_NODE_18]: { name: 'JavaScript (Node.js 18.15.0)', id: 93 },
  [LANG_KEYS.JAVASCRIPT_NODE_20]: { name: 'JavaScript (Node.js 20.17.0)', id: 97 },
  [LANG_KEYS.JAVASCRIPT_NODE_22]: { name: 'JavaScript (Node.js 22.08.0)', id: 102 },
  [LANG_KEYS.KOTLIN_1_3]: { name: 'Kotlin (1.3.70)', id: 78 },
  [LANG_KEYS.KOTLIN_2_1]: { name: 'Kotlin (2.1.10)', id: 111 },
  [LANG_KEYS.LUA]: { name: 'Lua (5.3.5)', id: 64 },
  [LANG_KEYS.MULTI_FILE_PROGRAM]: { name: 'Multi-file program', id: 89 },
  [LANG_KEYS.OBJECTIVE_C]: { name: 'Objective-C (Clang 7.0.1)', id: 79 },
  [LANG_KEYS.OCAML]: { name: 'OCaml (4.09.0)', id: 65 },
  [LANG_KEYS.OCTAVE]: { name: 'Octave (5.1.0)', id: 66 },
  [LANG_KEYS.PASCAL]: { name: 'Pascal (FPC 3.0.4)', id: 67 },
  [LANG_KEYS.PERL]: { name: 'Perl (5.28.1)', id: 85 },
  [LANG_KEYS.PHP_7]: { name: 'PHP (7.4.1)', id: 68 },
  [LANG_KEYS.PHP_8]: { name: 'PHP (8.3.11)', id: 98 },
  [LANG_KEYS.PLAIN_TEXT]: { name: 'Plain Text', id: 43 },
  [LANG_KEYS.PROLOG]: { name: 'Prolog (GNU Prolog 1.4.5)', id: 69 },
  [LANG_KEYS.PYTHON_2]: { name: 'Python (2.7.17)', id: 70 },
  [LANG_KEYS.PYTHON_3_11]: { name: 'Python (3.11.2)', id: 92 },
  [LANG_KEYS.PYTHON_3_12]: { name: 'Python (3.12.5)', id: 100 },
  [LANG_KEYS.PYTHON_3_13]: { name: 'Python (3.13.2)', id: 109 },
  [LANG_KEYS.PYTHON_3_8]: { name: 'Python (3.8.1)', id: 71 },
  [LANG_KEYS.R_4]: { name: 'R (4.0.0)', id: 80 },
  [LANG_KEYS.R_4_4]: { name: 'R (4.4.1)', id: 99 },
  [LANG_KEYS.RUBY]: { name: 'Ruby (2.7.0)', id: 72 },
  [LANG_KEYS.RUST_1_40]: { name: 'Rust (1.40.0)', id: 73 },
  [LANG_KEYS.RUST_1_85]: { name: 'Rust (1.85.0)', id: 108 },
  [LANG_KEYS.SCALA]: { name: 'Scala (2.13.2)', id: 81 },
  [LANG_KEYS.SQL]: { name: 'SQL (SQLite 3.27.2)', id: 82 },
  [LANG_KEYS.SWIFT]: { name: 'Swift (5.2.3)', id: 83 },
  [LANG_KEYS.TYPESCRIPT_3]: { name: 'TypeScript (3.7.4)', id: 74 },
  [LANG_KEYS.TYPESCRIPT_5]: { name: 'TypeScript (5.0.3)', id: 94 },
  [LANG_KEYS.TYPESCRIPT_5_6]: { name: 'TypeScript (5.6.2)', id: 101 },
  [LANG_KEYS.VISUAL_BASIC_NET]: { name: 'Visual Basic.Net (vbnc 0.0.0.5943)', id: 84 },
};
